#server
server:
  port: 8082
  tomcat:
    use-relative-redirects: true
#DB start
basic:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:23306/basic_db?allowMultiQueries=true
    username: basic
    password: timfDev
    maximum-pool-size: 30
    minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
    showSql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    web:
      pageable:
        default-page-size: 10